name: Publish Latest Release to Modrinth

on:
  workflow_dispatch:

jobs:
  publish-modrinth:
    runs-on: ubuntu-latest
    steps:
      - name: Download Packs from Release
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: 'geofont-*'
        
      - name: Publish Geofont to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: YNuo4qic
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          status: draft
          loaders: minecraft
          game-versions: |-
            1.13.x
            1.14.x
            1.15.x
            1.16.x
            1.17.x
            1.18.x
            1.19.x
            1.20.x
            1.21.x
          files: 'geofont-mc-${{ inputs.release_version }}.zip'
          # Adds Caxton as an optional dependency
          dependencies: |-
            [{
                "project_id": 'k8iIgzXE',
                "dependency_type": 'optional'
            }]

      - name: Publish Edge to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 8rGGW5Iw
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          status: draft
          loaders: minecraft
          game-versions: |-
            1.13.x
            1.14.x
            1.15.x
            1.16.x
            1.17.x
            1.18.x
            1.19.x
            1.20.x
            1.21.x
          files: 'geofont-edge-mc-${{ inputs.release_version }}.zip'
          # Adds Caxton as an optional dependency
          dependencies: |-
            [{
                "project_id": 'k8iIgzXE',
                "dependency_type": 'optional'
            }]
